"""Story pool for 2026-10-08, written in public-broadcaster hourly-newscast style (see ../STYLE_GUIDE.md).
Each story: priority (1 = all formats, 2 = 7/5/2.5-min, 3 = 12-min/filler), text_medium (7-min),
text_extra (appended for 12-min), text_short (5-min), text_flash (2:30 headline). Facts and sources unchanged
from the research pass; keep {{VARIABLES}} intact."""
import json
X="https://x.com/i/trending/"
GT="https://www.geckoterminal.com/"
def S(id,seg,pri,headline,medium,extra,short,flash,urls,ts):
    return dict(id=id,segment=seg,priority=pri,headline=headline,text_medium=medium,text_extra=extra,text_short=short,text_flash=flash,source_urls=urls,timestamp=ts)
stories=[
# ---------------- MEMECOIN MARKETS ----------------
S("pumpfun-deployers","trenches",1,"Pump.fun criticized over data on token creators' earnings",
 "The memecoin launch platform Pump.fun is facing criticism online after figures circulated suggesting its most active token creators have earned large sums while most tokens lose nearly all their value. According to the figures, shared by several crypto commentators, the top twenty-five creators launched about seven hundred and seventy thousand tokens and earned roughly one hundred and twenty-eight million dollars. Only six of those tokens reached a market value of twenty million dollars. Some users are calling for a boycott. A widely shared quote attributing the criticism to Ethereum co-founder Vitalik Buterin could not be traced to any original statement.",
 "The same figures suggest about eighty-one per cent of those tokens fell more than ninety per cent from their peak. Supporters of the platform say participation is voluntary and point to the fees it shares with creators and holders.",
 "The memecoin platform Pump.fun is under criticism after figures circulated suggesting its top twenty-five token creators earned about one hundred and twenty-eight million dollars, while only six of their roughly seven hundred and seventy thousand tokens reached a twenty-million-dollar market value.",
 "Pump.fun faces criticism over figures suggesting top token creators profited while most tokens collapsed.",
 [X+"2108248375107658104",X+"2108299036629582056",X+"2107907614981943473"],"2026-10-09T01:05:14Z"),
S("pumpfun-pairs","trenches",1,"Pump.fun lets new tokens trade against any token launched on the platform",
 "Pump.fun also announced a change to how new tokens trade. Creators can now pair a new token against any token already launched on the platform, rather than only a short list of approved assets. The company says purchases of a new token will be routed through the token it is paired with, adding demand for that token. Pump.fun's own token, PUMP, was down about eleven per cent over the past day, according to CoinGecko.",
 "",
 "Pump.fun also announced today that new tokens can be paired against any token already on the platform, a change the company says adds demand for established tokens.",
 "Pump.fun expands trading pairs for new tokens.",
 [X+"2108272049940570568","https://www.coingecko.com/en/coins/pump-fun"],"2026-10-08T21:49:19Z"),
S("sol-trending","trenches",1,"Newly launched Solana tokens post extreme price swings",
 "Trading data show the extreme volatility of newly created tokens on the Solana blockchain. According to the market-data site GeckoTerminal, a token called TikTok, created just before noon Pacific time today, has risen more than sixteen hundred per cent, to a market value of about six hundred and eighty thousand dollars. Another, BORDR, is up about seventeen hundred per cent. A third, swordinu, traded about five million dollars' worth in a day and has lost ninety-nine point nine per cent of its value. Separately, a token called TWEETCRAFT doubled in price after dozens of accounts posted near-identical promotional messages, a pattern often associated with co-ordinated promotion.",
 "Other recently launched tokens on the list include SharkTank, down about sixty-four per cent, and SENTS, up about one hundred and fifty per cent. Most are only hours old and trade in small volumes, which can magnify price moves.",
 "Newly created Solana tokens continue to swing sharply. Market data show a token called TikTok, launched today, up more than sixteen hundred per cent, while another, swordinu, has lost nearly all of its value.",
 "New Solana tokens post gains above sixteen hundred per cent while others collapse.",
 [GT+"solana/pools/Bjhum36bzoYbheRgSpkZLZsttbPBDbJCDoeKA7o9N2o",GT+"solana/pools/4xp7kN4nVt19caq4kM629vL8vJEqpSFVdZAh27wvYPh8",GT+"solana/trending_pools","https://x.com/search?q=tweetcraft"],"2026-10-09T01:13:00Z"),
S("drains","trenches",1,"Trader reports $4M wallet theft in Singapore; BNB Chain project loses $12.5M",
 "Two security incidents are drawing attention. A cryptocurrency trader known online as Frogman says about four million dollars was taken from two of his digital wallets in the early morning during the TOKEN2049 industry conference in Singapore. He says the funds were then moved through privacy services that make them harder to trace. Separately, on the BNB Chain network, an administrator account for a project called 79thVault used special permissions to withdraw about twelve and a half million dollars from a trading pool. Negotiations over a reward for returning the funds are reported to be under way.",
 "Frogman's reported losses include about one point eight million dollars in a token called BP and one point five million in another called MARSCOIN. Security firms criticized 79thVault for not requiring multiple approvals, known as a multi-signature setup, for such withdrawals.",
 "A trader known as Frogman says about four million dollars was stolen from his digital wallets during a crypto conference in Singapore. Separately, about twelve and a half million dollars was withdrawn from a trading pool run by a project called 79thVault.",
 "A trader reports four million dollars stolen; a separate project loses twelve and a half million.",
 [X+"2107733816207171835",X+"2108154220373581849"],"2026-10-08T14:40:09Z"),
S("leverage-degens","trenches",2,"High-risk trader returns with large leveraged Bitcoin bet",
 "On the trading platform Hyperliquid, a trader known as AguilaTrades has opened a new bet on Bitcoin using forty times leverage, meaning borrowed money magnifies both gains and losses. The position covers two hundred bitcoin, bought near eighty-two thousand nine hundred dollars, and would be forcibly closed, or liquidated, at about eighty-one thousand five hundred. Bitcoin was trading near [[BTC_PRICE]] dollars as of [[PRICES_AS_OF_SPOKEN]]. The same trader has been liquidated thirty-three times before, with losses of about thirty-seven million dollars.",
 "Another large trader, known as Machi Big Brother, held a leveraged ether position worth about one hundred million dollars as of yesterday, with a liquidation level near twenty-five hundred dollars. Ether has since traded below that level. The status of that position could not be confirmed.",
 "A trader known as AguilaTrades has placed a forty-times-leveraged bet on Bitcoin that would be forcibly closed near eighty-one thousand five hundred dollars. Bitcoin is currently near [[BTC_PRICE]] dollars.",
 "A trader places a heavily leveraged Bitcoin bet.",
 [X+"2108193702803804444",X+"2107903670377701822"],"2026-10-08T13:57:13Z"),
S("laptop","trenches",3,"Hunter Biden report blames market makers for LAPTOP token collapse",
 "Hunter Biden has released a report on the collapse of LAPTOP, a memecoin he is associated with on the Base network. The token spiked and then fell ninety-eight per cent within an hour of its launch last month. The report blames two market makers, the firms paid to keep trading orderly, for supplying very little money to the market. It says one provided about fifty-two hundred dollars and withdrew it eighty-four seconds after the peak. It also says founders' tokens remained locked.",
 "","","Hunter Biden's report blames market makers for a token's ninety-eight per cent crash.",
 [X+"2107922838963335273"],"2026-10-08T07:13:35Z"),
S("stonk-whale","trenches",3,"Large sale of STONK token draws scrutiny",
 "On Solana, a large sale of the STONK token is drawing scrutiny. An early buyer known online as The Solstice reportedly turned about eighty thousand dollars into one point six million, then sold a large part of the holding, pushing the price down about ten per cent within minutes. Critics say a small number of large holders pose a risk to the token. Supporters describe the move as normal volatility.",
 "","","",[X+"2107981708255711619"],"2026-10-07T23:57:06Z"),
S("whuf","trenches",3,"Ethos Network's WHUF token falls below sale price in debut",
 "On the Base network, the WHUF token from Ethos Network began trading today and fell below its public sale price of four dollars and twenty cents. Buyers in the sale have a guarantee covering eighty-five per cent of the price, or about three dollars and fifty-seven cents. Market data show the token down about thirty-five per cent over the day.",
 "","","",[X+"2108241879112564947",GT+"base/trending_pools"],"2026-10-08T20:17:25Z"),
S("bsc-lobster","trenches",3,"Chinese-named token among most active on BNB Chain",
 "On BNB Chain, a token named with the Chinese characters for 'lobster' is among the most actively traded, with a market value of about fifty million dollars, up about fifteen per cent, and more than six million dollars in daily trading. The network's memecoin launch service, Four.meme, held promotional events in Singapore during conference week.",
 "","","",[GT+"bsc/trending_pools",X+"2107824439673164105"],"2026-10-09T01:13:00Z"),
# ---------------- CRYPTO MARKETS & POLICY ----------------
S("majors","broader",1,"Crypto markets: Bitcoin near [[BTC_PRICE_DIGITS]]",
 "Cryptocurrency prices [[MARKET_MOVE_PAST]] over the past day. As of [[PRICES_AS_OF_SPOKEN]], Bitcoin was trading near [[BTC_PRICE]] U.S. dollars, [[BTC_CHANGE]] over twenty-four hours. Ether, the second-largest cryptocurrency, was near [[ETH_PRICE]] dollars, [[ETH_CHANGE]]. Solana was near [[SOL_PRICE]] dollars, [[SOL_CHANGE]]. Earlier today, more than one billion dollars in leveraged trades were forcibly closed within twenty-four hours, most of them bets on rising prices. Traders pointed to comments on Iran, higher oil prices and bond yields, and expectations the U.S. Federal Reserve will keep policy tight.",
 "The total value of all cryptocurrencies is about [[TOTAL_MCAP]] dollars, [[TOTAL_MCAP_CHANGE]], according to CoinGecko. Saturday marks one year since a sharp market drop on October tenth, twenty twenty-five, which forced the closure of about nineteen billion dollars in positions, days after Bitcoin reached a record near one hundred and twenty-six thousand dollars.",
 "As of [[PRICES_AS_OF_SPOKEN]], Bitcoin was near [[BTC_PRICE]] U.S. dollars, [[BTC_CHANGE]] over twenty-four hours. Ether was near [[ETH_PRICE]] dollars, [[ETH_CHANGE]], and Solana near [[SOL_PRICE]], [[SOL_CHANGE]]. More than a billion dollars in leveraged trades were forcibly closed earlier today.",
 "Bitcoin is near [[BTC_PRICE]] dollars, [[BTC_CHANGE]] on the day.",
 ["https://www.coingecko.com/",X+"2108045012894433331",X+"2107668599901213099"],"2026-10-09T01:13:00Z"),
S("etf-flows","broader",1,"Bitcoin funds see largest daily withdrawals in months",
 "Investors pulled about four hundred and eighty-five million dollars from U.S. Bitcoin exchange-traded funds on Tuesday, October seventh, according to data from Farside Investors. These funds trade on stock exchanges and hold Bitcoin directly. BlackRock's fund accounted for about two hundred and eight million dollars of the outflow. It was the largest single day of withdrawals in months.",
 "Funds holding Solana also saw smaller withdrawals earlier in the week, though they have still taken in about one point six billion dollars since launch.",
 "Investors withdrew about four hundred and eighty-five million dollars from U.S. Bitcoin exchange-traded funds on Tuesday, led by BlackRock's fund.",
 "Bitcoin funds post their largest daily withdrawals in months.",
 [X+"2108063487284900039","https://farside.co.uk/btc/",X+"2107780814763094166"],"2026-10-08T15:11:39Z"),
S("esma-usdt","broader",1,"EU regulator orders phase-out of non-compliant stablecoins, including USDT",
 "European regulators are moving against the world's largest stablecoin, a cryptocurrency designed to hold a steady value of one U.S. dollar. The European Securities and Markets Authority issued guidance today telling licensed crypto firms to stop offering services for stablecoins that do not meet EU rules, including Tether's USDT, by January eighth, twenty twenty-seven. New purchases are to stop immediately, with existing holdings wound down under supervision.",
 "Major platforms including Coinbase, Kraken, Bybit and OKX are among those affected. Compliant alternatives are being discussed as replacements.",
 "The European Union's markets regulator has told licensed crypto firms to phase out stablecoins that do not meet EU rules, including Tether's USDT, by January eighth, twenty twenty-seven.",
 "EU regulator orders USDT phased out of licensed platforms.",
 [X+"2108165500786426247"],"2026-10-09T01:03:47Z"),
S("cftc","broader",1,"U.S. CFTC proceeds with crypto trading rules",
 "In the United States, the Commodity Futures Trading Commission is moving ahead with its own rules for cryptocurrency trading while legislation stalls in Congress. Chairman Michael Selig says the proposals would offer exchanges a voluntary path to federal registration. The proposals are now open for sixty days of public comment.",
 "Selig cited the collapse of the exchange FTX and stressed the right of individuals to hold their own cryptocurrency.",
 "The U.S. Commodity Futures Trading Commission is proceeding with its own crypto trading rules while legislation stalls in Congress.",
 "U.S. commodities regulator advances crypto trading rules.",
 [X+"2107129344044982554",X+"2107869689447682381"],"2026-10-08T22:25:38Z"),
S("dip-buyers","broader",2,"Strategy and Cardone Capital add to Bitcoin holdings",
 "Some companies are buying. Strategy, the firm formerly known as MicroStrategy, says it bought three hundred and thirty-four bitcoin, bringing its holdings to a record eight hundred and forty-eight thousand, at an average cost of about seventy-five thousand four hundred dollars each. Real estate firm Cardone Capital says it bought forty bitcoin today, worth about three point two million dollars.",
 "Strategy's holdings amount to more than four per cent of all the bitcoin that will ever exist.",
 "Strategy now holds a record eight hundred and forty-eight thousand bitcoin, and Cardone Capital bought forty more today.",
 "Strategy and Cardone Capital add to their Bitcoin holdings.",
 [X+"2107859404167037006",X+"2108330599295668662"],"2026-10-08T23:02:59Z"),
S("bunker-mode","broader",3,"Ethereum researchers urge caution on wallet security",
 "Ethereum researcher Justin Drake is urging holders to move funds to new, unused addresses, citing rapid progress by artificial intelligence in mathematics as a possible future threat to the cryptography that protects wallets. Ethereum co-founder Vitalik Buterin said the risks are real but warned against rushed changes. Others note no practical attack exists today.",
 "","","",[X+"2108015931213402260"],"2026-10-08T21:49:05Z"),
S("exchange-reserves","broader",3,"Bitcoin held on exchanges falls to seven-month low",
 "The amount of Bitcoin held on trading platforms has fallen to about two point six eight million coins, roughly six and a half per cent of the supply, after the largest one-day withdrawal in seven months on Tuesday. Analysts often read this as a sign that holders are moving coins into long-term storage, though it has not always led to higher prices.",
 "","","",[X+"2108079921281356202"],"2026-10-08T10:04:54Z"),
S("hype-otc","broader",3,"Hyperliquid transfers $330M in tokens to institution",
 "The developer of the Hyperliquid trading platform transferred three point seven five million of its HYPE tokens, worth about three hundred and thirty million dollars, to an unnamed institution in a private sale outside public markets. HYPE was trading near [[HYPE_PRICE]] dollars as of [[PRICES_AS_OF_SPOKEN]], [[HYPE_CHANGE]] over twenty-four hours, according to CoinGecko.",
 "","","",[X+"2108154223439597875","https://www.coingecko.com/en/coins/hyperliquid"],"2026-10-08T13:47:30Z"),
S("fnb","broader",3,"South African bank opens crypto trading to customers",
 "In South Africa, First National Bank has begun offering cryptocurrency trading to nearly nine million customers through a partnership with the local exchange VALR. Customers can buy Bitcoin, ether, XRP, Solana and USDT, starting from ten rand.",
 "","","",[X+"2107600938152468711"],"2026-10-07T17:03:20Z"),
S("abstract","broader",3,"Abstract network to shut down in December",
 "And the Abstract network, which runs on top of Ethereum, will shut down on December fifteenth, citing low trading activity and high costs. Projects built on it, including the BEARISH digital collectibles series, are moving to Ethereum's main network.",
 "","","",[X+"2108295762803302646"],"2026-10-08T20:43:33Z"),
# ---------------- EMERGING TRENDS ----------------
S("ai-characters","metas",1,"Tokens based on AI-generated characters draw traders",
 "Tokens built around characters created with artificial intelligence are drawing heavy trading this week. One, Frank Ashford, is based on an AI-generated lookalike of a well-known crypto trader. Its token has a market value of about six hundred and eighty thousand dollars, up about forty-seven per cent today, according to GeckoTerminal. Another, Jean Phil, is a character from videos by the AI company Higgsfield, which released a new short featuring him today. A token named after him is valued at about six point four million dollars, up about a third.",
 "Whether interest in these characters lasts beyond the current trend remains an open question.",
 "Tokens based on AI-generated characters, including Frank Ashford and Jean Phil, are among the most actively traded on Solana this week.",
 "Tokens based on AI-generated characters draw heavy trading.",
 ["https://x.com/WhaleInsider/status/2107493105045844009",X+"2108305878457995444",GT+"solana/pools/745ATaSSWxvry5qt1XVv9eXuG884hDvNJfvA2o82dNBi",GT+"solana/pools/4R8CiMnJWDNoes3fQi1ccPFJygPXazaHaWpHrN3rZeNj"],"2026-10-08T21:24:36Z"),
S("memestocks","metas",1,"Tokens linked to company shares gain attention",
 "Another trend combines memecoins with tokenized shares, which are digital versions of company stock traded on blockchains. At the TOKEN2049 conference, Jesse Pollak, who leads Coinbase's Base network, presented examples of such tokens and called tokenized shares the next major growth area for the industry. On Solana, a token called STONK remains among the most traded, with a market value of about one hundred and twenty million dollars.",
 "Several launch services have created dozens of these tokens, and listings are appearing on a network linked to the trading app Robinhood.",
 "Tokens linked to company shares are gaining attention. Base network lead Jesse Pollak called tokenized shares the industry's next major growth area.",
 "Tokens tied to company shares gain attention on Base and Solana.",
 [X+"2107892114243670355",GT+"solana/pools/zxTpi4BtaWX3mgdAPoezkMD1hxx8CdeCfrqXMWvSCLX","https://dexscreener.com/"],"2026-10-08T08:15:56Z"),
S("ai-agents","metas",1,"Research report on AI agents lifts Derive token",
 "Investors are also watching the overlap between artificial intelligence and crypto. A new report from Citrini Research argues that autonomous AI programs, known as agents, will increase demand for around-the-clock blockchain payments and tokenized assets. The report's suggested portfolio includes the tokens of Derive, Lighter and Ether.fi. Derive's token rose about twenty-four per cent today, according to CoinGecko.",
 "A separate BlackRock paper reports that in simulations with thirty-six AI models, Bitcoin was chosen as the preferred store of value about seventy-nine per cent of the time.",
 "A Citrini Research report on AI agents and crypto helped lift Derive's token about twenty-four per cent today.",
 "Derive's token rises after a research report on AI agents.",
 [X+"2108278826199576730","https://www.coingecko.com/en/coins/derive",X+"2107456357503054146",X+"2107685371853312390"],"2026-10-09T00:03:10Z"),
S("revenue-memes","metas",2,"Interest grows in memecoins that share revenue",
 "Some traders are favouring memecoins that pay holders a share of revenue. The Injective blockchain's new community fund bought ten per cent of NinjaCat, a Solana token that pays holders in Injective's token. NinjaCat's market value reportedly rose about one hundred and fifty per cent. One analyst argues tokens without revenue now struggle to exceed about four hundred million dollars in value. The investor known as Murad disagreed at TOKEN2049, predicting a memecoin will one day surpass Bitcoin.",
 "",
 "Injective's community fund bought ten per cent of NinjaCat, a Solana memecoin that shares revenue with holders.",
 "Interest grows in memecoins that share revenue with holders.",
 [X+"2108339292808392791",X+"2107574014038147522",X+"2107201161799590185"],"2026-10-08T23:37:31Z"),
S("ai-snipers","metas",3,"Automated AI trading tools spread among memecoin traders",
 "Traders are also sharing results from automated programs that scan new tokens, screen out likely scams and trade without human input. One user claims one hundred dollars grew to more than seventeen thousand over four nights. Such claims have not been independently verified.",
 "","","",[X+"2107919061854392628"],"2026-10-07T19:48:06Z"),
]
pool=dict(edition="2026-10-08",title_base="{{STATION_NAME}} News: Crypto and Digital Markets, Thursday, October 8, 2026",
 style="public-broadcaster hourly newscast (see STYLE_GUIDE.md)",
 generated_at="2026-10-08T18:35:00-07:00",data_snapshot_at="2026-10-08T18:13:00-07:00",
 disclaimer="This report is for information only and is not financial advice. Token mentions are news, not recommendations. Memecoin data is unverified.",
 segments=[dict(id="trenches",name="Memecoin Markets",intro="We begin with memecoins, speculative digital tokens often based on internet jokes or personalities."),
           dict(id="broader",name="Crypto Markets and Policy",intro="Turning now to the wider cryptocurrency market."),
           dict(id="metas",name="Emerging Trends",intro="Finally, a look at the themes shaping speculative trading this week.")],
 intro_long="{{TIME_OF_DAY_GREETING}}. It's {{TIME_SPOKEN}}. This is {{STATION_NAME}} News. I'm {{ANCHOR_NAME}}. Cryptocurrency prices [[MARKET_MOVE_PRESENT]], with Bitcoin near [[BTC_PRICE]] dollars. European regulators order the stablecoin USDT phased out of licensed platforms. And the memecoin platform Pump.fun faces criticism over how much its top token creators earn. This report is for information only and is not financial advice.",
 intro_short="{{TIME_OF_DAY_GREETING}}. It's {{TIME_SPOKEN}}. This is {{STATION_NAME}} News. I'm {{ANCHOR_NAME}}. This report is not financial advice.",
 intro_flash="It's {{TIME_SPOKEN}}. This is {{STATION_NAME}} News. I'm {{ANCHOR_NAME}}.",
 outro_long="Prices quoted are as of [[PRICES_AS_OF_SPOKEN]] and can change quickly. This report is not financial advice. That's the news for this hour. I'm {{ANCHOR_NAME}}.",
 outro_short="Prices are as of [[PRICES_AS_OF_SPOKEN]]. That's the news for this hour. I'm {{ANCHOR_NAME}}.",
 outro_flash="That's the news for this hour. I'm {{ANCHOR_NAME}}.",
 market_snapshot=dict(prices_as_of="2026-10-08T18:13:00-07:00", source="coingecko",
   assets=dict(BTC=dict(usd=81701,change_24h_pct=-2.04),ETH=dict(usd=2474.07,change_24h_pct=-4.18),
               SOL=dict(usd=109.06,change_24h_pct=-6.48),HYPE=dict(usd=84.32,change_24h_pct=-4.91)),
   **{"global":dict(total_mcap_usd=2776352738348,total_mcap_change_24h_pct=-5.16)}),
 stories=stories)
json.dump(pool,open(__file__.replace("_make_pool_","").replace(".py",".pool.json"),"w"),indent=1,ensure_ascii=False)
print(len(stories))
